[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/*.jsx"
[headers.values]
Content-Type = "text/javascript"